name: Development build

on:
  workflow_call:
    input:
      targetPlatform:
        required: true
        type: string

      customParameters:
        required: false
        type: string

jobs:
  build:
    if: ${{ github.ref == 'refs/heads/dx/package-builds' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install vendor
        run: |
          curl ${{ secrets.VENDOR_URL }} -o vendor.zip
          yarn vendor:unpack
          rm vendor.zip

      # - uses: actions/cache@v3
      #   with:
      #     path: Library
      #     key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
      #     restore-keys: |
      #       Library-

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ inputs.targetPlatform }}
          customParameters: ${{ inputs.customParameters }}

      - uses: actions/upload-artifact@v3
        with:
          name: Build-${{ inputs.targetPlatform }}
          path: build/${{ inputs.targetPlatform }}

      - run: echo "artifact_name=Build-"${{ inputs.targetPlatform }} >> $GITHUB_OUTPUT
