name: Build and package macOS

on: workflow_call

jobs:
  build:
    name: 'Build for macOS'
    uses: ./.github/workflows/build.yml
    with:
      target_platform: StandaloneOSX
    secrets: inherit

  package_macos:
    name: Package macOS build
    needs: build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: installers/macos

      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          run-id: ${{ needs.build.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: public

      - run: find .

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: 'macOS DMG'
      #     path: 'Output/Install Pop Pixie.exe'
