name: Build and package macOS

# To create a signing certificate:
#   1. openssl req -newkey rsa:2048 -keyout pop-pixie.key -out pop-pixie.csr
#   2. Sign with Apple as a Developer ID Application
#   3. openssl x509 -in pop-pixie.cer -inform DER -out pop-pixie.pem -outform PEM
#   4. openssl pkcs12 -export -out pop-pixie.p12 -inkey pop-pixie.key -in pop-pixie.pem # You must specify an export password
#   5. base64 -i pop-pixie.p12 | pbcopy
#   6. pbpaste | gh secret set MACOS_CERTIFICATE
#   6. gh secret set MACOS_CERTIFICATE_PWD # The export password
#   7. security find-identity -v # Get the long alphanumeric string
#   8. gh secret set MACOS_IDENTITY_ID

on: workflow_call

jobs:
  # build:
  #   name: 'Build for macOS'
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     target_platform: StandaloneOSX
  #   secrets: inherit

  package_macos:
    name: Package macOS build
      # needs: build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: installers/macos

      # - uses: actions/download-artifact@v4
      #   with:
      #     name: ${{ needs.build.outputs.artifact_name }}
      #     run-id: ${{ needs.build.outputs.run_id }}
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     path: installers/macos/public

      - run: find .

      # https://localazy.com/blog/how-to-automatically-sign-macos-apps-using-github-actions
      - run: 'echo $MACOS_CERTIFICATE | base64 - --decode > certificate.p12'
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
      - run: 'security create-keychain -p password build.keychain'
      - run: 'security default-keychain -s build.keychain'
      - run: 'security unlock-keychain -p password build.keychain'
      - run: 'security import certificate.p12 -P $MACOS_CERTIFICATE_PWD -k build.keychain -T /usr/bin/codesign'
        env:
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      - run: 'security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k password build.keychain'
      - run: '/usr/bin/codesign --force -s $MACOS_IDENTITY_ID ./path/to/you/app -v'
        env:
          MACOS_IDENTITY_ID: ${{ secrets.MACOS_IDENTITY_ID }}

      # - run: hdiutil create -srcfolder installers/macos/public -volname 'Install Pop Pixie' 'Install Pop Pixie.dmg'

      - uses: actions/upload-artifact@v4
        with:
          name: 'macOS DMG'
          path: 'Install Pop Pixie.dmg'
