name: Upload to Steam

on: workflow_call

jobs:
  steam:
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows build
        uses: actions/download-artifact@v3
        with:
          name: Build-StandaloneWindows64
          path: build/windows

      - name: Download macOS Artifact
        uses: actions/download-artifact@v3
        with:
          name: Build-StandaloneOSX
          path: build/macOS

      - uses: game-ci/steam-deploy@v3
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
          appId: ${{ secrets.STEAM_APP_ID }}
          rootPath: build
          depot1Path: windows
          depot2Path: macOS
          releaseBranch: pull-request
