name: Test

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install vendor
        run: ./install_vendor.sh ${{ secrets.vendor_url }}

      # PulseAudio does not work in Docker container
      - name: Patch FMOD to disable sound
        run: |
          sed -i'' \
          's/result = coreSystem.setOutput(outputType);/result = coreSystem.setOutput(FMOD.OUTPUTTYPE.NOSOUND);/' \
          Assets/Plugins/FMOD/src/RuntimeManager.cs

      - name: Install Yarn dependencies
        run: yarn install

      - name: Run tests
        uses: 12joan/ci-unity-test-runner@main
        env:
          # gh secret set UNITY_LICENSE < /Library/Application\ Support/Unity/Unity_lic.ulf
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload screenshots to Percy
        run: yarn percy:upload
        if: always()
        env:
          # gh secret set PERCY_TOKEN <a Percy Web token>
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: Upload results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test results
          path: artifacts
