name: Build and package Windows

on: push

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      target_platform: StandaloneWindows64
      custom_parameters: -development
    secrets: inherit

  package_windows:
    name: Package Windows build
    needs: build
    runs-on: windows-latest

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          run-id: ${{ needs.build.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: public

      - run: dir
      - run: dir public
