name: Build and package Windows

on:
  workflow_call:
    inputs:
      initial_scene:
        required: true
        type: string
      branch_name:
        required: true
        type: string
      commit_hash:
        required: true
        type: string

jobs:
  build:
    name: 'Build for Windows'
    uses: ./.github/workflows/build.yml
    with:
      target_platform: StandaloneWindows64
      initial_scene: ${{ inputs.initial_scene }}
      branch_name: ${{ inputs.branch_name }}
      commit_hash: ${{ inputs.commit_hash }}
    secrets: inherit

  package_windows:
    name: Package Windows build
    needs: build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: installers/windows

      - uses: actions/download-artifact@v4
        with:
          name: Build-StandaloneWindows64
          run-id: ${{ github.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: public

      - name: Compile installer
        uses: anderbellstudios/Inno-Setup-Action
        with:
          path: ./installers/windows/pop-pixie.iss
          options: /O+

      - uses: actions/upload-artifact@v4
        with:
          name: 'Windows Installer'
          path: 'installers/windows/Output/Install Pop Pixie.exe'
